# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: ''
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: theme
labextension_name: mytheme
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: mytheme
repository: ''
test: true
viewer_name: ''

